# Generated by Django 2.2.10 on 2020-06-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translate',
            field=models.CharField(default='翻译', max_length=255, verbose_name='翻译'),
        ),
        migrations.AlterField(
            model_name='word',
            name='content',
            field=models.CharField(max_length=32, unique=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='word',
            name='list',
            field=models.ManyToManyField(default='', to='word_list.WordList', verbose_name='列表名'),
        ),
    ]
