# Generated by Django 2.2.10 on 2020-06-27 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word_list', '0003_auto_20200627_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_list.WordList')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_list.Word')),
            ],
        ),
    ]
