# Generated by Django 2.2.10 on 2020-06-27 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('word_list', '0004_userword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userword',
            options={'verbose_name_plural': '用户单词'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name_plural': '单词'},
        ),
        migrations.AlterModelOptions(
            name='wordlist',
            options={'verbose_name_plural': '单词list'},
        ),
        migrations.AddField(
            model_name='wordlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 6, 42, 56, 535616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='单词表名'),
        ),
    ]
