# Generated by Django 2.2.10 on 2020-06-27 06:52

from django.db import migrations
import django.utils.timezone
import word_list.models


class Migration(migrations.Migration):

    dependencies = [
        ('word_list', '0005_auto_20200627_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='created',
            field=word_list.models.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='userword',
            name='modified',
            field=word_list.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='word',
            name='created',
            field=word_list.models.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='word',
            name='modified',
            field=word_list.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='modified',
            field=word_list.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='created',
            field=word_list.models.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
    ]
