# Generated by Django 2.2.10 on 2020-06-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_list', '0006_auto_20200627_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='list',
        ),
    ]
