# Generated by Django 2.2.10 on 2020-07-18 02:28

from django.db import migrations
import word_list.models


class Migration(migrations.Migration):

    dependencies = [
        ('word_list', '0007_remove_word_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordlist',
            options={'verbose_name_plural': '用户单词List'},
        ),
        migrations.AddField(
            model_name='wordlist',
            name='data',
            field=word_list.models.JSONField(default={}, verbose_name='所有数据'),
            preserve_default=False,
        ),
    ]
