# Generated by Django 2.2.10 on 2020-07-18 02:35

from django.db import migrations
import word_list.models


class Migration(migrations.Migration):

    dependencies = [
        ('word_list', '0008_auto_20200718_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlist',
            name='data',
        ),
        migrations.AddField(
            model_name='word',
            name='data',
            field=word_list.models.JSONField(default={}, verbose_name='所有数据'),
            preserve_default=False,
        ),
    ]
